const nav=document.getElementById('nav');const button=document.getElementById('menuButton');const links=document.getElementById('navLinks');
function updateNav(){nav.classList.toggle('scrolled',window.scrollY>40)}updateNav();window.addEventListener('scroll',updateNav,{passive:true});
button.addEventListener('click',()=>{const open=links.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close menu':'Open menu')});
links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');button.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const form=document.getElementById('accessForm');const success=document.getElementById('success');const messages={name:'Enter your full name',email:'Enter a valid work email',company:'Enter your company name',role:'Enter your role',category:'Select a product category',details:'Tell us a bit more, at least 10 characters'};
function validField(field){const small=field.parentElement.querySelector('small');let ok=field.checkValidity();if(field.name==='details'&&field.value.trim().length<10)ok=false;if(!ok){small.textContent=messages[field.name]||'Complete this field'}else small.textContent='';return ok}
form.addEventListener('submit',e=>{e.preventDefault();const fields=[...form.querySelectorAll('input,select,textarea')];if(!fields.every(validField))return;const data=Object.fromEntries(new FormData(form).entries());const stored=JSON.parse(localStorage.getItem('bazi_early_access_submissions')||'[]');stored.push({...data,submittedAt:new Date().toISOString()});localStorage.setItem('bazi_early_access_submissions',JSON.stringify(stored));console.log('Early access request submitted:',data);form.hidden=true;success.hidden=false});
form.querySelectorAll('input,select,textarea').forEach(field=>field.addEventListener('blur',()=>validField(field)));document.getElementById('another').addEventListener('click',()=>{form.reset();form.hidden=false;success.hidden=true;form.querySelectorAll('small').forEach(s=>s.textContent='')});
