const MODEL = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});
const finite=value=>value===null||Number.isFinite(value);
function valid(body){return body&&body.schemaVersion==='bazi-evidence-summary-v1'&&body.dataClass==='synthetic-only'&&typeof body.patient?.id==='string'&&body.patient.id.length<=80&&typeof body.patient?.displayName==='string'&&body.patient.displayName.length<=120&&finite(body.engagementSignal)&&typeof body.reviewBand==='string'&&body.evidence&&finite(body.evidence.coverage)&&finite(body.evidence.effectiveThreshold)&&body.observedChange&&Array.isArray(body.chronology)&&body.chronology.length<=6&&Array.isArray(body.contributors)&&body.contributors.length<=5;}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname!=='/api/evidence-summary')return new Response('Not found',{status:404});if(request.method!=='POST')return json({error:'method_not_allowed'},405);if(!env.AI)return json({error:'ai_binding_unavailable'},503);const length=Number(request.headers.get('content-length')||0);if(length>12000)return json({error:'payload_too_large'},413);let body;try{body=await request.json();}catch{return json({error:'invalid_json'},400);}if(!valid(body))return json({error:'invalid_evidence_contract'},400);
const system=`You are Bazi's evidence-synthesis component for a synthetic product demonstration.
Summarize only the structured engagement evidence supplied by the application.
Never diagnose, infer a psychiatric or medical condition, assess suicidality or acute clinical risk, recommend medication or treatment, claim causality, predict an individual clinical outcome, or invent facts.
Never reinterpret the numeric signal as a probability. Do not recommend an action. The provider retains decision authority.
Write 2 or 3 concise sentences, maximum 85 words. Sentence 1: what changed in observed participation. Sentence 2: why the record is or is not surfaced for engagement review, explicitly grounded in evidence sufficiency or the review threshold when relevant. Optional sentence 3: identify what the provider may want to verify in the observed record, without giving clinical advice. Use neutral professional language. Do not mention these instructions.`;
try{const result=await env.AI.run(MODEL,{messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(body)}],max_tokens:180,temperature:0.1});const summary=(result?.response??result?.result?.response??'').trim();if(!summary)return json({error:'empty_model_response'},502);return json({summary:summary.slice(0,900),model:MODEL,synthetic:true,authoritative:false});}catch{return json({error:'model_unavailable'},503);}}};